module.exports = {
  ci: {
    collect: {
      // Just use local host lhci figures out the port for the ci build
      url: [
        'https://www.unilever.com/',
        'https://www.unilever.co.uk/',
        'https://www.unilever.it/',
        'https://www.hul.co.in/',
        'https://www.unilever.pk/',
        'https://www.unilever.com.lk/',
        'https://www.unileverusa.com/',
        'https://www.unilever.ca/',
        'https://www.unilever.com.tr/',
        'https://www.unilever.ru/',
        'https://www.unilever.co.jp/',
        'https://www.unilever.com.cn/',
        'https://www.unilever.co.kr/',
        'https://www.unilever.com.tw/',
        'https://www.unilever.com.bd/',
        'https://www.unilever.com.br/',
        'https://www.unilever.com.mx/',
        'https://www.unilever.com.ar/',
        'https://www.unilever.co.id/',
        'https://www.unilever.com.my/',
        'https://www.unilever.com.sg/',
        'https://www.unilever.com.vn/',
        'https://www.unilever.co.il/',
        'https://www.unilever.co.uk/',
        'https://www.unilever.co.il/',
        'https://www.unilever.dk/',
        'https://www.unilever.fi/',
        'https://www.unilever.se/',
        'https://www.unilever.com.ph/',
        'https://www.unilever.co.th/',
        'https://www.unilever.com.au/',
        'https://www.unilever.fr/',
        'https://www.unilever.be/',
        'https://www.unilever.nl/',
        'https://www.unilever.hu/',
        'https://www.unilever.de/',
        'https://www.unilever.es/',
        'https://www.unilever.it/',
        'https://www.unilever.cz/',
        'https://www.unilever.sk/',
        'https://www.unilever.gr/',
        'https://www.unilever.pl/',
        'https://www.unilever-fima.com/',
        'https://www.unilever.ro/',
        'https://www.unilever-ewa.com/',
        'https://www.unilever.co.za/',
        'https://www.unilever.com.hk',
        'https://www.unilever.tt',
        'https://www.unilever.ua/',
        'https://www.unilever.ee/',
      ],
    },
    upload: {
      target: 'temporary-public-storage',
    },
    assert: {
      assertions: {
        'categories:performance': ['error', { minScore: 0.9 }],
        'categories:accessibility': ['error', { minScore: 0.8 }],
        'categories:best-practices': ['error', { minScore: 0.92 }],
        'categories:seo': ['error', { minScore: 0.9 }],
      },
    },
  },
}
